# Generated by Django 3.2.4 on 2021-06-24 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('upvoted', models.IntegerField()),
                ('showcased', models.IntegerField()),
                ('followers', models.IntegerField()),
                ('created', models.IntegerField()),
                ('collections', models.IntegerField()),
                ('following', models.IntegerField()),
                ('github', models.URLField()),
            ],
        ),
    ]
