# Generated by Django 3.2.4 on 2021-06-24 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='github',
            field=models.URLField(default=''),
        ),
    ]
